-- Seed NC scratch-off library (store_id = NULL means shared library row)
-- Scraped from nclottery.com/scratch-off on 2026-04-26.
-- Re-run is safe: ON CONFLICT does nothing if the same (state, game_number) is already present.

CREATE UNIQUE INDEX IF NOT EXISTS idx_games_library_state_number
  ON games(state, game_number)
  WHERE store_id IS NULL;

INSERT INTO games (store_id, game_number, name, price, state, status, source) VALUES
  (NULL, 39,  '20 Years',                       20.00, 'NC', 'active', 'scraped'),
  (NULL, 38,  'Big Cash Blowout',               10.00, 'NC', 'active', 'scraped'),
  (NULL, 37,  'Prize Link Connect',              5.00, 'NC', 'active', 'scraped'),
  (NULL, 36,  'Easy $100s',                      2.00, 'NC', 'active', 'scraped'),
  (NULL, 35,  '$100,000 Cash Payday',           30.00, 'NC', 'active', 'scraped'),
  (NULL, 34,  'LOTERIA MULTIPLIER',             10.00, 'NC', 'active', 'scraped'),
  (NULL, 33,  '$500 Frenzy',                     5.00, 'NC', 'active', 'scraped'),
  (NULL, 32,  '500X The Cash',                  50.00, 'NC', 'active', 'scraped'),
  (NULL, 31,  '50X The Cash',                   10.00, 'NC', 'active', 'scraped'),
  (NULL, 30,  '20X The Cash',                    5.00, 'NC', 'active', 'scraped'),
  (NULL, 29,  '10X The Cash',                    2.00, 'NC', 'active', 'scraped'),
  (NULL, 28,  '5X The Cash',                     1.00, 'NC', 'active', 'scraped'),
  (NULL, 27,  'Stacks of Cash',                 20.00, 'NC', 'active', 'scraped'),
  (NULL, 26,  'Cash King',                       5.00, 'NC', 'active', 'scraped'),
  (NULL, 25,  '777',                             2.00, 'NC', 'active', 'scraped'),
  (NULL, 24,  '200X The Cash',                  30.00, 'NC', 'active', 'scraped'),
  (NULL, 23,  '$10 MONOPOLY',                   10.00, 'NC', 'active', 'scraped'),
  (NULL, 22,  '$5 MONOPOLY',                     5.00, 'NC', 'active', 'scraped'),
  (NULL, 18,  'Peppermint Payout',               5.00, 'NC', 'active', 'scraped'),
  (NULL, 15,  'Ultimate Blowout',               50.00, 'NC', 'active', 'scraped'),
  (NULL, 14,  'Magnificent Millions',           20.00, 'NC', 'active', 'scraped'),
  (NULL, 13,  'High Voltage Cash',               5.00, 'NC', 'active', 'scraped'),
  (NULL, 12,  'Cash Drop',                       2.00, 'NC', 'active', 'scraped'),
  (NULL, 11,  '$1,000,000 Bonus Match',         10.00, 'NC', 'active', 'scraped'),
  (NULL, 10,  'Double Your Money',               5.00, 'NC', 'active', 'scraped'),
  (NULL, 8,   'Ruby Red 7s',                    20.00, 'NC', 'active', 'scraped'),
  (NULL, 7,   'Cashword King',                  10.00, 'NC', 'active', 'scraped'),
  (NULL, 5,   '$50 Frenzy',                      1.00, 'NC', 'active', 'scraped'),
  (NULL, 4,   'Carolina Black Premier',         30.00, 'NC', 'active', 'scraped'),
  (NULL, 3,   'Hot $2,000',                     10.00, 'NC', 'active', 'scraped'),
  (NULL, 2,   'LOTERIA Fiesta',                  5.00, 'NC', 'active', 'scraped'),
  (NULL, 1,   '5 Times Lucky',                   5.00, 'NC', 'active', 'scraped'),
  (NULL, 996, '$1,000,000 Triple Play',         10.00, 'NC', 'active', 'scraped'),
  (NULL, 995, '$200,000 Triple Play',            5.00, 'NC', 'active', 'scraped'),
  (NULL, 994, '$25,000 Triple Play',             2.00, 'NC', 'active', 'scraped'),
  (NULL, 993, '$5,000 Triple Play',              1.00, 'NC', 'active', 'scraped'),
  (NULL, 992, '$2 MILLION VAULT',               20.00, 'NC', 'active', 'scraped'),
  (NULL, 990, 'LADY LUCK',                       2.00, 'NC', 'active', 'scraped'),
  (NULL, 988, 'Emerald 10s',                    10.00, 'NC', 'active', 'scraped'),
  (NULL, 985, 'MAX-A-MILLION',                  30.00, 'NC', 'active', 'scraped'),
  (NULL, 981, '50X The Cash',                   10.00, 'NC', 'active', 'scraped'),
  (NULL, 980, '20X The Cash',                    5.00, 'NC', 'active', 'scraped'),
  (NULL, 976, '100X The Cash',                  20.00, 'NC', 'active', 'scraped'),
  (NULL, 975, '$1,000,000 Money Rush',          10.00, 'NC', 'active', 'scraped'),
  (NULL, 972, '$8 Million Money Maker',         50.00, 'NC', 'active', 'scraped'),
  (NULL, 959, 'LOTERIA',                         3.00, 'NC', 'active', 'scraped'),
  (NULL, 952, 'Millionaire Bucks',              30.00, 'NC', 'active', 'scraped'),
  (NULL, 951, 'Win Big',                        20.00, 'NC', 'active', 'scraped'),
  (NULL, 949, 'Xtreme Cashword',                 5.00, 'NC', 'active', 'scraped'),
  (NULL, 948, 'JUMBO BUCKS',                    10.00, 'NC', 'active', 'scraped'),
  (NULL, 947, 'MEGA BUCKS',                      5.00, 'NC', 'active', 'scraped'),
  (NULL, 946, 'Junior BIG OL BUCKS',             2.00, 'NC', 'active', 'scraped'),
  (NULL, 944, '$50,000 Payout',                 20.00, 'NC', 'active', 'scraped'),
  (NULL, 940, 'Supreme 7s',                     30.00, 'NC', 'active', 'scraped'),
  (NULL, 939, '$80 Million Cash Blowout',       10.00, 'NC', 'active', 'scraped'),
  (NULL, 932, 'Instant Millions',               20.00, 'NC', 'active', 'scraped'),
  (NULL, 928, '$400,000 Jackpot',                5.00, 'NC', 'active', 'scraped'),
  (NULL, 925, '200X The Cash',                  30.00, 'NC', 'active', 'scraped'),
  (NULL, 917, '$2,000,000 Diamond Deluxe',      20.00, 'NC', 'active', 'scraped'),
  (NULL, 892, 'Black Titanium',                 30.00, 'NC', 'active', 'scraped'),
  (NULL, 876, '$5,000,000 Ultimate',            30.00, 'NC', 'active', 'scraped'),
  (NULL, 868, '100X The Cash',                  20.00, 'NC', 'active', 'scraped')
ON CONFLICT (state, game_number) WHERE store_id IS NULL DO NOTHING;
